# Generated by Django 5.0.1 on 2024-01-30 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eupmyeondodng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest_adm_code_nm', models.CharField(max_length=255)),
                ('adm_code_nm', models.CharField(max_length=255)),
                ('adm_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest_adm_code_nm', models.CharField(max_length=255)),
                ('adm_code_nm', models.CharField(max_length=255)),
                ('adm_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='re',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest_adm_code_nm', models.CharField(max_length=255)),
                ('adm_code_nm', models.CharField(max_length=255)),
                ('adm_code', models.CharField(max_length=10, unique=True)),
                ('Eupmyeondodng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.eupmyeondodng')),
            ],
        ),
        migrations.CreateModel(
            name='Sigungu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest_adm_code_nm', models.CharField(max_length=255)),
                ('adm_code_nm', models.CharField(max_length=255)),
                ('adm_code', models.CharField(max_length=10, unique=True)),
                ('Sido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.sido')),
            ],
        ),
        migrations.AddField(
            model_name='eupmyeondodng',
            name='Sigungu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.sigungu'),
        ),
    ]
