# Generated by Django 5.0.1 on 2024-01-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eupmyeondodng',
            old_name='adm_code',
            new_name='admCode',
        ),
        migrations.RenameField(
            model_name='eupmyeondodng',
            old_name='adm_code_nm',
            new_name='admCodeNm',
        ),
        migrations.RenameField(
            model_name='eupmyeondodng',
            old_name='lowest_adm_code_nm',
            new_name='lowestAdmCodeNm',
        ),
        migrations.RenameField(
            model_name='re',
            old_name='adm_code',
            new_name='admCode',
        ),
        migrations.RenameField(
            model_name='re',
            old_name='adm_code_nm',
            new_name='admCodeNm',
        ),
        migrations.RenameField(
            model_name='re',
            old_name='lowest_adm_code_nm',
            new_name='lowestAdmCodeNm',
        ),
        migrations.RenameField(
            model_name='sido',
            old_name='adm_code',
            new_name='admCode',
        ),
        migrations.RenameField(
            model_name='sido',
            old_name='adm_code_nm',
            new_name='admCodeNm',
        ),
        migrations.RenameField(
            model_name='sido',
            old_name='lowest_adm_code_nm',
            new_name='lowestAdmCodeNm',
        ),
        migrations.RenameField(
            model_name='sigungu',
            old_name='adm_code',
            new_name='admCode',
        ),
        migrations.RenameField(
            model_name='sigungu',
            old_name='adm_code_nm',
            new_name='admCodeNm',
        ),
        migrations.RenameField(
            model_name='sigungu',
            old_name='lowest_adm_code_nm',
            new_name='lowestAdmCodeNm',
        ),
    ]
