# Generated by Django 5.0.1 on 2024-01-30 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_rename_adm_code_eupmyeondodng_admcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admDongList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowestAdmCodeNm', models.CharField(max_length=255)),
                ('admCodeNm', models.CharField(max_length=255)),
                ('admCode', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='re',
            name='Eupmyeondodng',
        ),
        migrations.RemoveField(
            model_name='sigungu',
            name='Sido',
        ),
        migrations.CreateModel(
            name='admReeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowestAdmCodeNm', models.CharField(max_length=255)),
                ('admCodeNm', models.CharField(max_length=255)),
                ('admCode', models.CharField(max_length=10, unique=True)),
                ('admDongList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.admdonglist')),
            ],
        ),
        migrations.RenameModel(
            old_name='Sido',
            new_name='admCodeList',
        ),
        migrations.CreateModel(
            name='admSiList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowestAdmCodeNm', models.CharField(max_length=255)),
                ('admCodeNm', models.CharField(max_length=255)),
                ('admCode', models.CharField(max_length=10, unique=True)),
                ('admCodeList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.admcodelist')),
            ],
        ),
        migrations.AddField(
            model_name='admdonglist',
            name='admSiList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.admsilist'),
        ),
        migrations.DeleteModel(
            name='Eupmyeondodng',
        ),
        migrations.DeleteModel(
            name='re',
        ),
        migrations.DeleteModel(
            name='Sigungu',
        ),
    ]
