# Generated by Django 5.0.1 on 2024-01-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_admdonglist_remove_re_eupmyeondodng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admdonglist',
            old_name='admSiList',
            new_name='AdmSiList',
        ),
        migrations.RenameField(
            model_name='admreelist',
            old_name='admDongList',
            new_name='AdmDongList',
        ),
        migrations.RenameField(
            model_name='admsilist',
            old_name='admCodeList',
            new_name='AdmCodeList',
        ),
    ]
