# Generated by Django 5.0.1 on 2024-01-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_rename_admsilist_admdonglist_admsilist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admcodelist',
            name='admCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='admdonglist',
            name='admCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='admreelist',
            name='admCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='admsilist',
            name='admCode',
            field=models.CharField(max_length=10),
        ),
    ]
