# Generated by Django 5.0.1 on 2024-01-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0005_alter_admcodelist_admcode_alter_admdonglist_admcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admdonglist',
            name='AdmSiList',
        ),
        migrations.RemoveField(
            model_name='admreelist',
            name='AdmDongList',
        ),
        migrations.RemoveField(
            model_name='admsilist',
            name='AdmCodeList',
        ),
    ]
